language: python
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install coveralls -r requirements-dev.txt

script:
  - py.test --cov cabby

after_success:
  - coveralls
